import { cn } from "@/lib/utils";
import { CtaLink } from "./cta-link";
import { TEXT_BODY, TEXT_H1 } from "./tokens";

// Fictional wordmarks only (four match the demo's seed brands, two invented).
// Never a real company: see CLAUDE.md content and safety rules.
const TRUSTED_BY = ["Tallyfox", "Orbitly", "Quillhaus", "Beaconly", "Vanterra", "Ledgerly"];

function LinkedinMark() {
  return (
    <span
      aria-hidden
      className="flex size-4 items-center justify-center rounded-[4px] bg-[#0a66c2] text-[9px] font-bold leading-none text-white"
    >
      in
    </span>
  );
}

export function Hero() {
  return (
    <section className="relative overflow-hidden bg-linear-to-b from-white via-[#eaf3fb] to-white">
      <div aria-hidden className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -top-24 left-[8%] size-72 rounded-full bg-white/70 blur-3xl" />
        <div className="absolute top-6 right-[6%] size-96 rounded-full bg-white/60 blur-3xl" />
        <div className="absolute top-44 left-1/3 size-64 rounded-full bg-white/50 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-4xl px-4 pt-20 pb-24 text-center sm:px-6 sm:pt-28 sm:pb-28">
        <span className="inline-flex items-center gap-2 rounded-full border border-line bg-white/80 px-4 py-1.5 text-sm font-medium text-ink-soft shadow-sm">
          <LinkedinMark />
          Where B2B brands work with creators
        </span>

        <h1 className={cn(TEXT_H1, "mt-6")}>The B2B LinkedIn Creator Marketplace.</h1>

        <p className={cn(TEXT_BODY, "mx-auto mt-6 max-w-2xl")}>
          Find the creators your buyers already trust, launch campaigns in days, and track the
          clicks, leads and pipeline generated by every post.
        </p>

        <div className="mt-9 flex flex-wrap items-center justify-center gap-4">
          <CtaLink href="/brand" arrow>
            Launch a campaign
          </CtaLink>
          <CtaLink href="#how-it-works" variant="text" arrow>
            See how it works
          </CtaLink>
        </div>

        <div className="mt-20">
          <p className="text-xs font-semibold tracking-[0.14em] text-ink-mute uppercase">
            Trusted by modern B2B teams
          </p>
          <ul className="mt-6 flex flex-wrap items-center justify-center gap-x-10 gap-y-4">
            {TRUSTED_BY.map((name) => (
              <li
                key={name}
                className="text-lg font-semibold tracking-tight text-ink-mute/80 sm:text-xl"
              >
                {name}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
